### ISSUE TITLE
Can't add 3rd URL

### ISSUE THREAD

**Issue by adityak80** [edward-qin/daily_opener_extension#1]
Can type the 3rd URL, but it does not get saved - even if I click 'Add' after typing the 3rd URL.

**Comment by edward-qin** [comment]
Hey thanks for opening this! Do you have an example? I can't seem to reproduce this issue.

**Comment by adityak80** [comment]
Went to record a screen recording for you and was not able to repro myself
-- it seems to be working. Will try to investigate next time it behaves
like that. Thanks for your add-on.

Cheers!

**Comment by edward-qin** [comment]
Sounds good!
